<a href="https://colab.research.google.com/github/chethan5045/Sensor_Temperature_Analysis/blob/main/Chethan_M__Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Given data
data = np.array([
    [22.5, 19.0, 31.2, 28.7, 25.1],
    [17.3, 22.8, 30.5, 26.4, 21.9],
    [33.1, 29.6, 18.4, 24.0, 27.8],
    [20.2, 23.5, 31.9, 28.1, 22.6]
])

# -------------------- Task 1 --------------------
# Print shape of data
print("Shape of data:", data.shape)

# Compute mean temperature per station (row-wise mean)
mean_per_station = data.mean(axis=1)
print("Mean temperature per station:", mean_per_station)

# -------------------- Task 2 --------------------
# Extract temperatures above 28°C using boolean mask
above_28 = data[data > 28]
print("Temperatures above 28°C:", above_28)

# -------------------- Task 3 --------------------
# Normalize entire array to range [0, 1]
normalized = (data - data.min()) / (data.max() - data.min())

# Round to 2 decimal places
normalized_rounded = np.round(normalized, 2)

print("Normalized data (rounded to 2 decimals):")
print(normalized_rounded)

Shape of data: (4, 5)
Mean temperature per station: [25.3  23.78 26.58 25.26]
Temperatures above 28°C: [31.2 28.7 30.5 33.1 29.6 31.9 28.1]
Normalized data (rounded to 2 decimals):
[[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
